// AUTO-GENERATED by real-estate-reels-web — do not hand-edit.
// Real estate listing config — consumed by Root.tsx.

export const PROJECT_FOLDER = "Projects/Sample Listing";

export const LISTING_PHOTOS: string[] = [
];

export const AGENT_HEADSHOT_FILE = "";
export const BROKERAGE_LOGO_FILE = "";
export const BACKGROUND_MUSIC_FILE = "";

export const PROPERTY_ADDRESS = "123 Magnolia Lane";
export const CITY             = "Austin";
export const STATE            = "TX";
export const LISTING_PRICE    = "$1,250,000";
export const BEDS             = "4";
export const BATHS            = "3";
export const SQUARE_FEET      = "2,840";

export const AGENT_NAME       = "Jordan Carter";
export const AGENT_PHONE      = "(512) 555-0142";
export const AGENT_EMAIL      = "jordan@bluestonere.com";
export const BROKERAGE_NAME   = "Bluestone Realty";
export const CTA_TEXT         = "Schedule a Showing";

export const OPEN_HOUSE_DATE  = "";
export const OPEN_HOUSE_TIME  = "";
export const SHORT_DESCRIPTION = "";
export const NEIGHBORHOOD     = "";
export const MLS_LINK         = "";

export const CLIP_DURATION_SECONDS = 18;
