export const PROJECTS = [
  {
    "id": "artist-alley-break-even-sites",
    "name": "artist-alley-break-even",
    "folderPath": "C:\\Sites\\artist-alley-break-even",
    "location": "C:\\Sites",
    "projectType": "Web App",
    "status": "Testing",
    "dateModified": "2026-05-10",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/artist-alley-break-even",
    "notes": ""
  },
  {
    "id": "asset-approval-link-sites",
    "name": "asset-approval-link",
    "folderPath": "C:\\Sites\\asset-approval-link",
    "location": "C:\\Sites",
    "projectType": "Utility Tool",
    "status": "Haven\u2019t Started",
    "dateModified": "2026-04-10",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "baby-coat-check-flutter-sites",
    "name": "baby_coat_check_flutter",
    "folderPath": "C:\\Sites\\baby_coat_check_flutter",
    "location": "C:\\Sites",
    "projectType": "Mobile App",
    "status": "Testing",
    "dateModified": "2026-05-08",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/baby-coat-check-flutter",
    "notes": ""
  },
  {
    "id": "backjack-test-sites",
    "name": "backjack-test",
    "folderPath": "C:\\Sites\\backjack-test",
    "location": "C:\\Sites",
    "projectType": "Game/Experiment",
    "status": "Testing",
    "dateModified": "2026-05-03",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/bjack",
    "notes": ""
  },
  {
    "id": "bas-website-starter-sites",
    "name": "bas-website-starter",
    "folderPath": "C:\\Sites\\bas-website-starter",
    "location": "C:\\Sites",
    "projectType": "Business Website",
    "status": "Working",
    "dateModified": "2026-05-04",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/britten-aerial-services",
    "notes": ""
  },
  {
    "id": "bbw-creator-directory-sites",
    "name": "bbw-creator-directory",
    "folderPath": "C:\\Sites\\bbw-creator-directory",
    "location": "C:\\Sites",
    "projectType": "Directory",
    "status": "Haven\u2019t Started",
    "dateModified": "2026-05-03",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "britten-aerial-sites",
    "name": "britten-aerial",
    "folderPath": "C:\\Sites\\britten-aerial",
    "location": "C:\\Sites",
    "projectType": "Business Website",
    "status": "Working",
    "dateModified": "2026-05-02",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/britten-aerial-services",
    "notes": ""
  },
  {
    "id": "britten-woodworking-eleventy-sites",
    "name": "britten-woodworking-eleventy",
    "folderPath": "C:\\Sites\\britten-woodworking-eleventy",
    "location": "C:\\Sites",
    "projectType": "Business Website",
    "status": "Paused",
    "dateModified": "2026-03-21",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/britten-woodworking",
    "notes": ""
  },
  {
    "id": "brittenwoodworking-new-sites",
    "name": "brittenwoodworking-new",
    "folderPath": "C:\\Sites\\brittenwoodworking-new",
    "location": "C:\\Sites",
    "projectType": "Business Website",
    "status": "Working",
    "dateModified": "2026-05-04",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/britten-woodworking",
    "notes": ""
  },
  {
    "id": "caities-portfolio-sites",
    "name": "caities_portfolio",
    "folderPath": "C:\\Sites\\caities_portfolio",
    "location": "C:\\Sites",
    "projectType": "Portfolio",
    "status": "Working",
    "dateModified": "2026-05-02",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/caitlin-portfolio",
    "notes": ""
  },
  {
    "id": "coding-project-tracker-sites",
    "name": "coding-project-tracker",
    "folderPath": "C:\\Sites\\coding-project-tracker",
    "location": "C:\\Sites",
    "projectType": "Utility Tool",
    "status": "Working",
    "dateModified": "2026-05-11",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "cropcheck-sites",
    "name": "cropcheck",
    "folderPath": "C:\\Sites\\cropcheck",
    "location": "C:\\Sites",
    "projectType": "Utility Tool",
    "status": "Testing",
    "dateModified": "2026-05-02",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "dehumidifier-sizing-calculator-sites",
    "name": "dehumidifier-sizing-calculator",
    "folderPath": "C:\\Sites\\dehumidifier-sizing-calculator",
    "location": "C:\\Sites",
    "projectType": "Affiliate Tool",
    "status": "Launched",
    "dateModified": "2026-05-03",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/dehumidifier-sizing-calculator",
    "notes": ""
  },
  {
    "id": "deposit-letter-sites",
    "name": "deposit-letter",
    "folderPath": "C:\\Sites\\deposit-letter",
    "location": "C:\\Sites",
    "projectType": "Legal/Letter Tool",
    "status": "Launched",
    "dateModified": "2026-04-19",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/deposit-letter",
    "notes": ""
  },
  {
    "id": "fastlisting-sites",
    "name": "fastlisting",
    "folderPath": "C:\\Sites\\fastlisting",
    "location": "C:\\Sites",
    "projectType": "Media Tool",
    "status": "Working",
    "dateModified": "2026-05-04",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/fastlisting",
    "notes": ""
  },
  {
    "id": "finalfile-sites",
    "name": "FinalFile",
    "folderPath": "C:\\Sites\\FinalFile",
    "location": "C:\\Sites",
    "projectType": "Utility Tool",
    "status": "Testing",
    "dateModified": "2026-05-08",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/FinalFile",
    "notes": ""
  },
  {
    "id": "friendly-winner-sites",
    "name": "friendly-winner",
    "folderPath": "C:\\Sites\\friendly-winner",
    "location": "C:\\Sites",
    "projectType": "Finance/Tracker",
    "status": "Working",
    "dateModified": "2026-05-07",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/friendly-winner",
    "notes": ""
  },
  {
    "id": "front-porch-craft-fair-sites",
    "name": "front-porch-craft-fair",
    "folderPath": "C:\\Sites\\front-porch-craft-fair",
    "location": "C:\\Sites",
    "projectType": "Event Website",
    "status": "Testing",
    "dateModified": "2026-04-23",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "fuzmaster-github-io-sites",
    "name": "fuzmaster.github.io",
    "folderPath": "C:\\Sites\\fuzmaster.github.io",
    "location": "C:\\Sites",
    "projectType": "Portfolio",
    "status": "Launched",
    "dateModified": "2026-04-20",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/fuzmaster.github.io",
    "notes": ""
  },
  {
    "id": "health-dashboard-sites",
    "name": "health-dashboard",
    "folderPath": "C:\\Sites\\health-dashboard",
    "location": "C:\\Sites",
    "projectType": "Dashboard",
    "status": "Paused",
    "dateModified": "2026-04-18",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "keep7-sites",
    "name": "keep7",
    "folderPath": "C:\\Sites\\keep7",
    "location": "C:\\Sites",
    "projectType": "Utility Tool",
    "status": "Testing",
    "dateModified": "2026-05-04",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/keep7",
    "notes": ""
  },
  {
    "id": "maximum-tips-website-sites",
    "name": "maximum-tips-website",
    "folderPath": "C:\\Sites\\maximum-tips-website",
    "location": "C:\\Sites",
    "projectType": "Website",
    "status": "Launched",
    "dateModified": "2026-04-29",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/maximum-tips-website",
    "notes": ""
  },
  {
    "id": "mvp-social-chaos-engine-sites",
    "name": "MVP-Social-Chaos-Engine",
    "folderPath": "C:\\Sites\\MVP-Social-Chaos-Engine",
    "location": "C:\\Sites",
    "projectType": "Experiment",
    "status": "Paused",
    "dateModified": "2026-04-09",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "new-portfolio-sites",
    "name": "New Portfolio",
    "folderPath": "C:\\Sites\\New Portfolio",
    "location": "C:\\Sites",
    "projectType": "Portfolio",
    "status": "Working",
    "dateModified": "2026-05-05",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/portfolio-jb",
    "notes": ""
  },
  {
    "id": "new-portfolio-video-sites",
    "name": "new-portfolio-video",
    "folderPath": "C:\\Sites\\new-portfolio-video",
    "location": "C:\\Sites",
    "projectType": "Portfolio",
    "status": "Paused",
    "dateModified": "2026-04-05",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "peabody-ready-hub-sites",
    "name": "peabody-ready-hub",
    "folderPath": "C:\\Sites\\peabody-ready-hub",
    "location": "C:\\Sites",
    "projectType": "Local Utility",
    "status": "Testing",
    "dateModified": "2026-05-10",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/peabody-ready-hub",
    "notes": ""
  },
  {
    "id": "podcast-slicer-sites",
    "name": "podcast-slicer",
    "folderPath": "C:\\Sites\\podcast-slicer",
    "location": "C:\\Sites",
    "projectType": "Media Tool",
    "status": "Testing",
    "dateModified": "2026-05-10",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/podcast-slicer",
    "notes": ""
  },
  {
    "id": "quotecheck-home-sites",
    "name": "quotecheck-home",
    "folderPath": "C:\\Sites\\quotecheck-home",
    "location": "C:\\Sites",
    "projectType": "Homeowner Tool",
    "status": "Testing",
    "dateModified": "2026-05-10",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/quotecheck-home",
    "notes": ""
  },
  {
    "id": "quoterotor-sites",
    "name": "quoterotor",
    "folderPath": "C:\\Sites\\quoterotor",
    "location": "C:\\Sites",
    "projectType": "Business Tool",
    "status": "Needs Marketing",
    "dateModified": "2026-04-21",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/quoterotor",
    "notes": ""
  },
  {
    "id": "roast-my-gear-sites",
    "name": "roast-my-gear",
    "folderPath": "C:\\Sites\\roast-my-gear",
    "location": "C:\\Sites",
    "projectType": "Game/Utility Tool",
    "status": "Testing",
    "dateModified": "2026-05-11",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/osrs-gear-roast",
    "notes": ""
  },
  {
    "id": "scamcheck-family-mobile-sites",
    "name": "scamcheck-family-mobile",
    "folderPath": "C:\\Sites\\scamcheck-family-mobile",
    "location": "C:\\Sites",
    "projectType": "Mobile App",
    "status": "Testing",
    "dateModified": "2026-05-08",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/scamcheck-family-mobile",
    "notes": ""
  },
  {
    "id": "srt-fixer-sites",
    "name": "srt-fixer",
    "folderPath": "C:\\Sites\\srt-fixer",
    "location": "C:\\Sites",
    "projectType": "Media Tool",
    "status": "Launched",
    "dateModified": "2026-05-08",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/srt-fixer",
    "notes": ""
  },
  {
    "id": "stop-hemp-ban-fixed-sites",
    "name": "stop-hemp-ban-fixed",
    "folderPath": "C:\\Sites\\stop-hemp-ban-fixed",
    "location": "C:\\Sites",
    "projectType": "Advocacy Site",
    "status": "Launched",
    "dateModified": "2026-04-28",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/stop-hemp-ban",
    "notes": ""
  },
  {
    "id": "strictsub-sites",
    "name": "strictsub",
    "folderPath": "C:\\Sites\\strictsub",
    "location": "C:\\Sites",
    "projectType": "Media Tool",
    "status": "Launched",
    "dateModified": "2026-05-10",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/strictsub",
    "notes": ""
  },
  {
    "id": "todo-codextest-sites",
    "name": "todo-codextest",
    "folderPath": "C:\\Sites\\todo-codextest",
    "location": "C:\\Sites",
    "projectType": "Experiment",
    "status": "Testing",
    "dateModified": "2026-04-10",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/todo-codextest",
    "notes": ""
  },
  {
    "id": "twitch-assets-sites",
    "name": "twitch-assets",
    "folderPath": "C:\\Sites\\twitch-assets",
    "location": "C:\\Sites",
    "projectType": "Asset Tool",
    "status": "Working",
    "dateModified": "2026-05-06",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/twitch-assets",
    "notes": ""
  },
  {
    "id": "brittenwoodworking-trailer-remotion",
    "name": "brittenwoodworking-trailer",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\brittenwoodworking-trailer",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-02-24",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "calcmydehumidifier-ads-remotion",
    "name": "calcmydehumidifier-ads",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\calcmydehumidifier-ads",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Working",
    "dateModified": "2026-05-07",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "genera-reels-remotion",
    "name": "Genera-Reels",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\Genera-Reels",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-05-02",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "genera-reels-web-remotion",
    "name": "Genera-Reels-Web",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\Genera-Reels-Web",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Working",
    "dateModified": "2026-05-11",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "growmode-trailer-graphics-remotion",
    "name": "growmode-trailer-graphics",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\growmode-trailer-graphics",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-02-20",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "hf-reels-remotion",
    "name": "hf-reels",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\hf-reels",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-03-05",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "hf-reels-v2-remotion",
    "name": "hf-reels-v2",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\hf-reels-v2",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-03-06",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "hfp-overlays-remotion",
    "name": "HFP-Overlays",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\HFP-Overlays",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-02-22",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "hfp-overlays-v2-remotion",
    "name": "HFP-Overlays-v2",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\HFP-Overlays-v2",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-02-22",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "hfp-overlays-v3-remotion",
    "name": "HFP-Overlays-v3",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\HFP-Overlays-v3",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-03-02",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "highfunctioning-graphics-remotion",
    "name": "highfunctioning-graphics",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\highfunctioning-graphics",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Working",
    "dateModified": "2026-05-11",
    "dateAdded": "2026-05-11",
    "githubUrl": "https://github.com/fuzmaster/highfunctioninggraphics",
    "notes": ""
  },
  {
    "id": "highfunctioning-intros-remotion",
    "name": "highfunctioning-intros",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\highfunctioning-intros",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-03-09",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "highfunctioning-test-claude-remotion",
    "name": "highfunctioning-test-claude",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\highfunctioning-test-claude",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Testing",
    "dateModified": "2026-05-02",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "kinetic-subs-remotion",
    "name": "kinetic-subs",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\kinetic-subs",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Working",
    "dateModified": "2026-04-30",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "like-subscribe-remotion",
    "name": "like-subscribe",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\like-subscribe",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Testing",
    "dateModified": "2026-03-03",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "max-reels-project-remotion",
    "name": "max-reels-project",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\max-reels-project",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-04-01",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "my-video-remotion",
    "name": "my-video",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\my-video",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-02-07",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "real-estate-remotion-app-remotion",
    "name": "real-estate-remotion-app",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\real-estate-remotion-app",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Working",
    "dateModified": "2026-03-03",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "samkanter-intro-remotion",
    "name": "samkanter-intro",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\samkanter-intro",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-03-02",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "samkanter-reels-remotion",
    "name": "samkanter-reels",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\samkanter-reels",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-03-03",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "screensaver-loopingvideos-remotion",
    "name": "screensaver-loopingvideos",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\screensaver-loopingvideos",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-03-01",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "shannon-ig-reels-remotion",
    "name": "shannon-ig-reels",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\shannon-ig-reels",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-02-23",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "shannon-reels-remotion",
    "name": "shannon-reels",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\shannon-reels",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-02-20",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "showreel-video-remotion",
    "name": "showreel-video",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\showreel-video",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-03-03",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "test-remotion",
    "name": "test",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\test",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Experiment",
    "status": "Testing",
    "dateModified": "2026-02-07",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "woodworking-showreel-remotion",
    "name": "woodworking-showreel",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\woodworking-showreel",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-02-19",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  },
  {
    "id": "woodworking-temp-remotion",
    "name": "woodworking-temp",
    "folderPath": "D:\\Dropbox\\Remotion Projects\\woodworking-temp",
    "location": "D:\\Dropbox\\Remotion Projects",
    "projectType": "Remotion/Video",
    "status": "Paused",
    "dateModified": "2026-02-19",
    "dateAdded": "2026-05-11",
    "githubUrl": "",
    "notes": ""
  }
];
